### ISSUE TITLE
Error in print_running_summary

### ISSUE THREAD

**Issue by tschmitt** [tschmitt/job_control#1]
Receive the following error when a job attempts to print out the running step summary.

`
ERROR, UNEXPECTED EXCEPTION
unsupported operand type(s) for -: 'str' and 'datetime.datetime'
Traceback (most recent call last):
  File "/mnt/linux_scripts/prod/job_control/run_job.py", line 256, in <module>
    results = main()
  File "/mnt/linux_scripts/prod/job_control/run_job.py", line 138, in main
    job.print_running_summary(options.running_delay)
  File "/mnt/c/Users/tschmitt/Documents/projects/linux_scripts/job_control/job_control/jobs.py", line 591, in print_running_summary
    cur_running_msg = cur_running_msg + '%s: %s (pid: %s) (name: %s)' % (step, self.format_date(datetime.today()) - steps[step]['job_status']['start_time'], self.steps[step]['job_status']['pid'], self.steps[step]['name'])  + '\n'
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.datetime'
`

The fix (line 591) should be the following, but needs to be tested:
`cur_running_msg = cur_running_msg + '%s: %s (pid: %s) (name: %s)' % (step, datetime.today() - steps[step]['job_status']['start_time'], self.steps[step]['job_status']['pid'], self.steps[step]['name'])  + '\n'`

**Comment by tschmitt** [comment]
Fixed function per ticket comments.
Released v1.7.001
